### ISSUE TITLE
[UI] Improve the design of Food Recipe Card.

### ISSUE THREAD

**Issue by apurv-1** [apurv-1/FoodRecipe#1]
The food recipe card is simple, use your creativity to design it.

**Comment by Sanchit-Soni** [comment]
I would like to work on this issue.

**Comment by ghost** [comment]
I will make the card look absoulutely phenomenal, can I aslo contribute?

**Comment by SourabhKanade** [comment]
UI can be improved very well and the design of the card as well. Interested to modify

**Comment by apurv-1** [comment]
Great! Please go ahead and open your PRs @Atharv777 @SourabhKanade
