### ISSUE TITLE
Correct calorie unit and add serves

### ISSUE THREAD

**Issue by josef-butler** [apurv-1/FoodRecipe#6]
Hey there!

I noticed that calories were shown to be in grams which is an incorrect unit for calories. From this I thought of a few changes that could be made:

- Remove the unit of measurement for calories, as "Calories" is already written
- Add the number of serves a recipe makes
- Use that to calculate the number of calories per serve, rather than for the whole recipe, as it's a bit more practical for a user

Before/after screenshots of the changes I can make are below. If you'd like me to go ahead, could you please assign the issue to me? Thanks!

**Before**

![foodrecipe-before](https://user-images.githubusercontent.com/48168036/136677337-4bfc16a9-1db0-4b8a-9ff1-7f668a81b808.png)

**After**

![foodrecipe-after](https://user-images.githubusercontent.com/48168036/136677338-d021699b-1663-492e-8e25-8a34f0530e55.png)

**Comment by apurv-1** [comment]
Seems good, Please go ahead and open a PR with changes!
